spring:
  application:
    name: authorization
  profiles:
    active:
      - default
  config:
    import: configserver:http://localhost:7000
  security:
    user:
      name: "admin@bookstore.com"
      password: "admin@bookstore.com"
      roles:
        - "ADMIN"
    oauth2:
      authorizationserver:
        issuer: http://localhost:7030
        client:
          bookstore:
            registration:
              client-id: "bookstore"
              client-secret: "{noop}secret"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
                - "client_credentials"
              redirect-uris:
                - "http://127.0.0.1:8080/authorized"
              scopes:
                - "message:read"
                - "message:write"
            require-authorization-consent: true