server:
  port: 7030
 
eureka:
  instance:
    hostname: auth-server
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:7010/eureka/
      
spring:
  application:
    name: auth-server
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      discovery:
        locator:
          enabled: true # 基于向服务发现注册的服务创建路由
          lower-case-service-id: true
  security:
    user:
      name: user
      password: password
    oauth2:
      authorization-server:
        client:
          client-1:
            registration:
              client-id: "client"
              client-secret: "{noop}secret"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"


management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework.security: trace