server:
  port: 7030
spring:
  jackson:
    timeZone: GMT+8
    dateFormat: yyyy-MM-dd HH:mm:ss
  security:
    user:
      name: "admin@bookstore.com"
      password: "{bcrypt}$2a$10$BdYWnKbH7Kk5.JyJ5I4OGe.EoUjiTeU2hDY4y4SA62.nZ3maeIv5K"
      roles:
        - "ADMIN"
    oauth2:
      authorizationserver:
        issuer: http://localhost:7030
        client:
          bookstore:
            registration:
              client-id: "bookstore"
              client-secret: "{bcrypt}$2a$10$N0ull8s2QSOUG/BLO7l99uVkMx6Ofls3Knhfxm.56MTn5YU2uvIvy"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
                - "client_credentials"
              redirect-uris:
                - "http://127.0.0.1:8080/authorized"
              post-logout-redirect-uris:
                - "http://127.0.0.1:8080/"
              scopes:
                - "openid"
                - "user:read"
                - "user:write"
            require-authorization-consent: true

eureka:
  instance:
    preferIpAddress: true # 注册服务的IP，而不是服务器名称
  client:
    registerWithEureka: true
    fetchRegistry: true # 拉取注册表的本地副本
    serviceUrl:
      defaultZone: http://localhost:7010/eureka/ # Eureka服务的位置
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
  show-actuator: true

#Enable all Spring Boot Actuator endpoints.
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework.security: trace