server:
  port: 7030
 
eureka:
  instance:
    hostname: auth-server
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:7010/eureka/
      
spring:
  application:
    name: auth-server
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      discovery:
        locator:
          enabled: true # 基于向服务发现注册的服务创建路由
          lower-case-service-id: true
  security:
    user:
      name: janwee
      password: '{cipher}63ed5d612148bbb4389580149c87d747204ab8e17c907da7f4034e391711accb'
    oauth2:
      authorizationserver:
        client:
          oidc-client:
            registration:
              client-id: "client-1"
              client-secret: "{noop}secret-1"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
              redirect-uris:
                - "http://127.0.0.1:7030/login/oauth2/code/oidc-client"
              post-logout-redirect-uris:
                - "http://127.0.0.1:7030/"
              scopes:
                - "openid"
                - "profile"
            require-authorization-consent: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework.security: trace