server:
  port: 7030
 
eureka:
  instance:
    hostname: auth-server
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:7010/eureka/
      
spring:
  application:
    name: auth-server
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      discovery:
        locator:
          enabled: true # 基于向服务发现注册的服务创建路由
          lower-case-service-id: true
  security:
    oauth2:
      authorizationserver:
        issuer: http://auth-server:7030

management:
  endpoints:
    web:
      exposure:
        include: "*"