spring:
  datasource:
    url: "jdbc:h2:mem:bookstore-authorization;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE"
    driver-class-name: org.h2.Driver
  jpa:
    database: h2
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  security:
    user:
      password: "{bcrypt}$2a$10$BdYWnKbH7Kk5.JyJ5I4OGe.EoUjiTeU2hDY4y4SA62.nZ3maeIv5K"
    oauth2:
      authorizationserver:
        issuer: http://localhost:7030
        client:
          bookstore:
            registration:
              client-secret: "{bcrypt}$2a$10$N0ull8s2QSOUG/BLO7l99uVkMx6Ofls3Knhfxm.56MTn5YU2uvIvy"
              redirect-uris:
                - "http://127.0.0.1:7001/authorized"
              post-logout-redirect-uris:
                - "http://127.0.0.1:7001/"
          bookstore-frontend:
            registration:
              redirect-uris:
                - "http://127.0.0.1:8088/authorized"
              post-logout-redirect-uris:
                - "http://127.0.0.1:8088/"

eureka:
  client:
    service-url:
      defaultZone: http://eureka:7010/eureka/

logging:
  level:
    org.springframework.security: trace
