spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://authorization:18083/oauth2/jwks
  datasource:
    url: "jdbc:h2:mem:bookstore-book;MODE=PostgreSQL;INIT=CREATE SCHEMA IF NOT EXISTS book;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE"
    driver-class-name: org.h2.Driver
    hikari:
      connection-test-query: "SELECT 1"
  jpa:
    database: h2
    properties:
      jakarta:
        persistence:
          sharedCache:
            mode: ENABLE_SELECTIVE
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        cache:
          use_second_level_cache: false
          region:
            factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
        generate_statistics: true
    show-sql: true
    generate-ddl: true
  rabbitmq:
    username: guest
    password: guest
    addresses: rabbitmq:5672

eureka:
  client:
    service-url:
      defaultZone: http://eureka:18081/eureka/
