spring:
  cloud:
    stream:
      binders:
        boss:
          type: rabbit
      bindings:
        orderCreatedConsumer-in-0:
          destination: queue.order.created
        bookSoldOutSupplier-out-0:
          destination: queue.book.soldOut
          producer:
            confirm-ack-channel: queue.book.soldOut.confirm
        bookOrderedSupplier-out-0:
          destination: queue.book.ordered
          producer:
            confirm-ack-channel: queue.book.ordered.confirm
  rabbitmq:
    username: janwee
    password: '{cipher}63ed5d612148bbb4389580149c87d747204ab8e17c907da7f4034e391711accb'
    addresses: 142.171.184.180:5672
    # 开启生产者确认
    publisher-confirms: true
    publisher-returns: true
    # 消费者确认
    listener:
      simple:
        acknowledge-mode: manual
