spring:
  cloud:
    stream:
      binders:
        boss:
          type: rabbit
      function:
        definition: bookSoldOutSupplier;bookOrderedSupplier;orderCreatedConsumer
      bindings:
        orderCreatedConsumer-in-0:
          destination: queue.order.created
        bookSoldOutSupplier-out-0:
          destination: queue.book.soldOut
          producer:
            confirm-ack-channel: queue.book.soldOut.confirm
        bookOrderedSupplier-out-0:
          destination: queue.book.ordered
          producer:
            confirm-ack-channel: queue.book.ordered.confirm
  rabbitmq:
    username: guest
    password: guest
    addresses: 127.0.0.1:5672