spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://authorization:7030/oauth2/jwks
      client:
        registration:
          github:
            client-id: "${GITHUB_CLIENT_ID:replace-me}"
            client-secret: "${GITHUB_CLIENT_SECRET:replace-me}"
          bookstore:
            client-secret: "${BOOKSTORE_CLIENT_SECRET:secret}"
            redirect-uri: http://127.0.0.1:7001/authorized
        provider:
          spring:
            authorization-uri: http://localhost:7030/oauth2/authorize
            token-uri: http://authorization:7030/oauth2/token
            jwk-set-uri: http://authorization:7030/oauth2/jwks

eureka:
  instance:
    hostname: gateway
  client:
    service-url:
      defaultZone: http://eureka:7010/eureka/
