server:
  port: 8080
 
eureka:
  instance:
    hostname: gateway
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:7010/eureka/
      
spring:
  application:
    name: gateway
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      discovery:
        locator:
          enabled: true # 基于向服务发现注册的服务创建路由
          lower-case-service-id: true
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23li0TCedWOcZS8Dm7
            client-secret: 2848af385711ae2db49fe845eb5aaba455b70f4d
          bookstore:
            provider: spring
            client-id: bookstore
            client-secret: secret
            client-authentication-method: client_secret_basic
            authorization-grant-type: authorization_code
            redirect-uri: http://127.0.0.1:8080/authorized
            scope: user:read, user:write
            client-name: Spring
        provider:
          spring:
            authorization-uri: http://localhost:7030/oauth2/authorize
            token-uri: http://localhost:7030/oauth2/token
            jwk-set-uri: http://localhost:7030/oauth2/jwks

management:
  endpoints:
    web:
      exposure:
        include: "*"

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
  show-actuator: true