spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:18083/oauth2/jwks

eureka:
  client:
    service-url:
      defaultZone: http://localhost:18081/eureka/
