spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://authorization:7030/oauth2/jwks

eureka:
  instance:
    hostname: gateway
  client:
    service-url:
      defaultZone: http://eureka:7010/eureka/
