spring:
  cloud:
    stream:
      binders:
        boss:
          type: rabbit
      function:
        definition: orderCreatedSupplier;bookSoldOutConsumer;bookOrderedConsumer
      bindings:
        bookOrderedConsumer-in-0:
          destination: queue.book.ordered
        bookSoldOutConsumer-in-0:
          destination: queue.book.soldOut
        orderCreatedSupplier-out-0:
          destination: queue.order.created
  rabbitmq:
    username: guest
    password: guest
    addresses: 127.0.0.1:5672