spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/bookstore?currentSchema=order&useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true&serverTimezone=Asia/Shanghai
    username: dev
    password: dev
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    properties:
      hibernate:
    show-sql: true
    generate-ddl: true