spring:
  cloud:
    stream:
      binders:
        boss:
          type: rabbit
      function:
        definition: orderCreatedSupplier;bookSoldOutConsumer;bookOrderedConsumer
      bindings:
        bookOrderedConsumer-in-0:
          destination: queue.book.ordered
        bookSoldOutConsumer-in-0:
          destination: queue.book.soldOut
        orderCreatedSupplier-out-0:
          destination: queue.order.created
  rabbitmq:
    username: janwee
    password: '{cipher}63ed5d612148bbb4389580149c87d747204ab8e17c907da7f4034e391711accb'
    addresses: 142.171.184.180:5672