spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:7030/oauth2/jwks
  datasource:
    url: "jdbc:h2:mem:bookstore-order;MODE=PostgreSQL;NON_KEYWORDS=ORDER;INIT=CREATE SCHEMA IF NOT EXISTS order;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE"
    driver-class-name: org.h2.Driver
  jpa:
    database: h2
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: true
    generate-ddl: true
  rabbitmq:
    username: guest
    password: guest
    addresses: 127.0.0.1:5672

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7010/eureka/
