server:
  port: 18082

spring:
  application:
    name: gateway
  profiles:
    default: local
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:18080}
  cloud:
    gateway:
      mvc:
        routes:
          - id: book
            uri: lb://book
            predicates:
              - Path=/book/**
            filters:
              - StripPrefix=1
          - id: order
            uri: lb://order
            predicates:
              - Path=/order/**
            filters:
              - StripPrefix=1

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
