server:
  port: 18084

spring:
  application:
    name: book
  profiles:
    default: local
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:18080}
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  jpa:
    open-in-view: true
  cloud:
    stream:
      binders:
        boss:
          type: rabbit
      function:
        definition: bookSoldOutSupplier;bookOrderedSupplier;orderCreatedConsumer
      bindings:
        orderCreatedConsumer-in-0:
          destination: queue.order.created
        bookSoldOutSupplier-out-0:
          destination: queue.book.soldOut
          producer:
            confirm-ack-channel: queue.book.soldOut.confirm
        bookOrderedSupplier-out-0:
          destination: queue.book.ordered
          producer:
            confirm-ack-channel: queue.book.ordered.confirm

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
