DROP SCHEMA IF EXISTS "book" CASCADE;
CREATE SCHEMA "book";

DROP TABLE IF EXISTS "book"."books";

CREATE TABLE "book"."books"
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    book_name  VARCHAR(255)                            NOT NULL,
    amount     INTEGER                                 NOT NULL,
    price      DECIMAL                                 NOT NULL,
    publish_by date                                    NOT NULL,
    publisher  VARCHAR(255)                            NOT NULL,
    author_id  BIGINT                                  NOT NULL,
    CONSTRAINT pk_books PRIMARY KEY (id)
);