spring:
  jpa:
    database: postgresql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: true
    generate-ddl: false
  datasource:
    driver-class-name: org.postgresql.Driver
    username: janwee
    password: '{cipher}63ed5d612148bbb4389580149c87d747204ab8e17c907da7f4034e391711accb'
    jdbc-url: jdbc:postgresql://192.168.136.133:5432/janwee?currentSchema=author