spring:
  cloud:
    stream:
      binders:
        boss:
          type: rabbit
  #      bindings:
  #        event-in-order:
  #          destination: queue.order.event
  #        event-out:
  #          destination: queue.book.event
  rabbitmq:
    username: janwee
    password: '{cipher}63ed5d612148bbb4389580149c87d747204ab8e17c907da7f4034e391711accb'
    addresses: 192.168.136.133:5672