spring:
  jpa:
    database: postgresql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: true
    generate-ddl: false
  datasource:
    druid:
      url: jdbc:postgresql://192.168.136.133:5432/janwee?currentSchema=book&useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true&serverTimezone=Asia/Shanghai
      username: janwee
      password: janwee
      driver-class-name: org.postgresql.Driver