server:
  port: 7010
eureka:
  client:
    registerWithEureka: false # 不使用Eureka服务进行注册
    fetchRegistry: false # 不在本地缓存注册表信息
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ # Eureka服务的位置
  server:
    waitTimeInMsWhenSyncEmpty: 5 # 在服务器接收请求之前等待的初始时间
  instance:
    preferIpAddress: true
    hostname: localhost

spring:
  boot:
    admin:
      context-path: /admin